
[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2021"
name = "global_mouse_hook"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "3.0.0"
napi-derive = "3.0.0"
x11rb = "0.13.2"

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
strip = "symbols"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.62.2", features = [
  "Win32_Foundation",
  "Win32_UI_WindowsAndMessaging",
  "Win32_UI_Input_KeyboardAndMouse",
] }